### PR TITLE
Proposal for making multipart handling more practical

### PR DESCRIPTION
**Pull request by johannes85**
First of all: Thanks for implementing file uploads and multipart request parsing.

I tried to use it in a project, but there are some design decitions which makes this hard or for some cases impossible to use:

 * Bug: In SAPI mode, normal parameters are not added to the list of parts.
 * When handling a multipart form with File- and normal Input fields, the token parameter can't be validated by the xp-forge/frontend lib (when transfered as an hidden input field). This is because the parameters are merged with the multipart ones only when calling Request::multipart::parts/files. The workaround is to transfer the token as get parameter which is a security risk.
 * In general it is not possible to just read a parameter for example in a filter and parse the files later.
 * The merging of the multipart parameter with the request ones is an unexpected side effect when calling Request::multipart::parts/files.
 * Request::multipart::parts/files can't be called a second time.

I understand that it is designed this way, so you can read files as they are written to the server (without storing them in memory/hdd) but this behavior makes the multipart handling very unflexible.

So my proposal is to handle the file upload in the same way its handled by PHP and other frameworks like django (https://docs.djangoproject.com/en/3.1/topics/http/file-uploads/) or expressjs (https://www.npmjs.com/package/express-fileupload) by parsing the multipart data beforehand and storing the file on the hdd (or in memory for small files).

This pull request is a basic implementation of this behavior and there are some things missing:
 * Encoding handling of parameters sent by multipart request (Which I think is also missing in the current implementation)
 * A way to define the max size of the uploaded files

Optional features would be:
 * A way to hook into the storing of the uploaded file (like in django: https://docs.djangoproject.com/en/3.1/topics/http/file-uploads/) so you can for example implement a file upload progress meter or implement other file storage engines (or provide a way for the user to directly hook into the stream to get the current bahavior).

### CODE REVIEW

**Comment by johannes85** [comment]
@thekid Thanks for implementing multipart handling, but at this point it's not very usable for everiday forms, so I tried to implement it in a different way.

**Comment by thekid** [comment]
These "restrictions" as you feel them were made intentionally to allow streaming uploads. Your solution reverts back to what PHP does, with the problem that code inside a handler only gets executed *after* all files have been completely uploaded. For small images, no issue. When uploading gigabytes of video, you might want to be able to react to this (and e.g. stream them right to an S3 bucket, FTP server or what-you-have). xp-forge/web is intentionally supposed to be a more low-level.

However, I understand the part where you want to reject file uploads right in the moment when a CRSF token mismatch is detected. If you pass them in a hidden field *before* the file input elements you can also parse them from the request before handling the files - here we run into the inconsistency with the PHP SAPIs: There is no way to see in which order the parameters have been passed and which ones come before the files and which ones come after them, PHP has already separated them from the request. A guess could be to place all of the parameters *before* the files, which would be typically be correct for hidden fields, and incorrect for buttons, but would make it possible to implement the scenario described above in a way that works in both SAPIs and streamed server API.

**Comment by thekid** [comment]
You should be able to implement file upload handlers such as https://docs.djangoproject.com/en/3.1/topics/http/file-uploads/#upload-handlers by using filters:

```php
use io\{File, Folder};
use web\Filter;

class StoreFileUploads implements Filter {

  public function __construct(private Folder $storage) { }

  public function filter($request, $response, $invocation) {
     if (null === ($upload= $req->multipart())) return $invocation->proceed($request, $response);

     $uploads= [];
     foreach ($upload->files() as $name => $file) {
       $target= new File($this->storage, uniqid());
       $file->transfer($target);
       $uploads[$name]= $target;
     }

     try {
       return $invocation->proceed($request->pass('uploads', $uploads), $response);
     } finally {
       foreach ($uploads as $file) {
         $file->exists() || $file->delete();
       }
     }
  }
}
```

Then, attach these to your file upload route:

```php
use web\{Application, Filters};

class Uploads extends Application {

  public function routes() {
    $tmp= new Folder(...);
    return ['/files' => new Filters([new StoreFileUploads($tmp)], function($req, $res) {
       // Here, $req->params() will be have been merged and can be handled as usual
       // TBI
     })];
  }
}
```

Maybe we can add this to a small additional library (and maybe make it intelligent about storing smaller files to memory, and add upload progress meter handling). Would that be helpful?

**Comment by thekid** [comment]
> However, I understand the part where you want to reject file uploads right in the moment when a CRSF token mismatch is detected. If you pass them in a hidden field before the file input elements you can also parse them from the request before handling the files

Here's a patch for this:

```diff
diff --git a/src/main/php/web/Multipart.class.php b/src/main/php/web/Multipart.class.php
index 99edffc..401a849 100755
--- a/src/main/php/web/Multipart.class.php
+++ b/src/main/php/web/Multipart.class.php
@@ -12,34 +12,68 @@ use web\io\Part;
 class Multipart {
   const MIME = 'multipart/form-data';
 
-  private $request, $boundary;
+  private $parts, $params;
+  private $peeked= null;
 
   /**
    * Creates a new Multipart instance
    *
-   * @param  web.Request $request
-   * @param  web.Parameterized $type
+   * @param  iterable $parts
+   * @param  [:var] $params
    */
-  public function __construct($request, $type) {
-    $this->request= $request;
-    $this->boundary= $type->param('boundary');
+  public function __construct($parts, &$params) {
+    if ($parts instanceof \Iterator) {
+      $this->parts= $parts;
+    } else if ($parts instanceof \IteratorAggregate) {
+      $this->parts= $parts->getIterator();
+    } else {
+      $this->parts= new \ArrayIterator($parts);
+    }
+    $this->params= &$params;
+  }
+
+  /**
+   * Returns all parameters *before* files, parsing the request body until
+   * that position.
+   *
+   * @return web.io.Param[]
+   */
+  public function peek() {
+    if (null !== $this->peeked) return $this->peeked;
+
+    $this->peeked= [];
+    while ($this->parts->valid()) {
+      $part= $this->parts->current();
+      if (Part::PARAM !== $part->kind()) break;
+
+      parse_str($this->parts->key().'='.$part->value(), $params);
+      $this->params= array_merge_recursive($this->params, $params);
+      $this->parts->next();
+      $this->peeked[]= $part;
+    }
+    return $this->peeked;
   }
 
-  /** @return string */
-  public function boundary() { return $this->boundary; }
- 
   /**
    * Returns all parts - files and parameters.
    *
    * @return iterable
    */
   public function parts() {
-    foreach ($this->request->input()->parts($this->boundary) as $name => $part) {
+    if ($this->peeked) foreach ($this->peeked as $param) {
+      yield $param->name() => $param;
+    }
+    $this->peeked= [];
+
+    while ($this->parts->valid()) {
+      $name= $this->parts->key();
+      $part= $this->parts->current();
       if (Part::PARAM === $part->kind()) {
         parse_str($name.'='.$part->value(), $params);
-        $this->request->add($params);
+        $this->params= array_merge_recursive($this->params, $params);
       }
       yield $name => $part;
+      $this->parts->next();
     }
   }
 
@@ -49,14 +83,19 @@ class Multipart {
    * @return iterable
    */
   public function files() {
-    foreach ($this->request->input()->parts($this->boundary) as $name => $part) {
+    $this->peeked= [];
+
+    while ($this->parts->valid()) {
+      $name= $this->parts->key();
+      $part= $this->parts->current();
       $kind= $part->kind();
       if (Part::PARAM === $kind) {
         parse_str($name.'='.$part->value(), $params);
-        $this->request->add($params);
+        $this->params= array_merge_recursive($this->params, $params);
       } else if (Part::FILE === $kind) {
         yield $part->name() => $part;
       }
+      $this->parts->next();
     }
   }
 }
\ No newline at end of file
diff --git a/src/main/php/web/Request.class.php b/src/main/php/web/Request.class.php
index e5bb7cb..ce14a13 100755
--- a/src/main/php/web/Request.class.php
+++ b/src/main/php/web/Request.class.php
@@ -3,10 +3,11 @@
 use io\streams\{MemoryInputStream, Streams};
 use lang\Value;
 use util\{Objects, URI};
-use web\io\Input;
+use web\io\{Input, Part};
 
 class Request implements Value {
   private $stream= null;
+  private $multipart= null;
   private $lookup= [];
   private $headers= [];
   private $values= [];
@@ -116,9 +117,10 @@ class Request implements Value {
    * Parses payload into parameters and handles encoding (both cached)
    *
    * @see    http://www.w3.org/TR/html5/forms.html#application/x-www-form-urlencoded-encoding-algorithm
+   * @param  bool $peek Whether to peek multipart requests for parameters
    * @return void
    */
-  private function parse() {
+  private function parse($peek= true) {
     if (null !== $this->params) return;
 
     // Merge parameters from URL and urlencoded payload.
@@ -131,6 +133,12 @@ class Request implements Value {
     }
     parse_str($query, $this->params);
 
+    // Read multipart bodies up until the first non-parameter part
+    if (Multipart::MIME === $type->value()) {
+      $this->multipart= new Multipart($this->input()->parts($type->param('boundary')), $this->params);
+      $peek && $this->multipart->peek();
+    }
+
     // Be liberal in what we accept and support "; charset=XXX" although the spec
     // states this media type does not have parameters! Then, handle the special
     // parameter named "_charset_" as per spec.
@@ -176,17 +184,6 @@ class Request implements Value {
     }
   }
 
-  /**
-   * Adds parameters
-   *
-   * @param  [:var] $params
-   */
-  public function add($params) {
-    $this->parse();
-
-    $this->params= array_merge_recursive($this->params, $params);
-  }
-
   /**
    * Gets request parameters
    *
@@ -284,11 +281,8 @@ class Request implements Value {
    * @return ?web.io.Multipart
    */
   public function multipart() {
-    $type= Headers::parameterized()->parse($this->header('Content-Type'));
-    if (Multipart::MIME === $type->value()) {
-      return new Multipart($this, $type);
-    }
-    return null;
+    $this->parse(false);
+    return $this->multipart;
   }
 
   /**
diff --git a/src/main/php/xp/web/SAPI.class.php b/src/main/php/xp/web/SAPI.class.php
index 7a8bed2..c55bb1c 100755
--- a/src/main/php/xp/web/SAPI.class.php
+++ b/src/main/php/xp/web/SAPI.class.php
@@ -1,6 +1,6 @@
 <?php namespace xp\web;
 
-use web\io\{Buffered, Input, Output, ReadStream, ReadLength, WriteChunks, Incomplete};
+use web\io\{Buffered, Input, Output, Param, ReadStream, ReadLength, WriteChunks, Incomplete};
 
 /**
  * Wrapper for PHP's Server API ("SAPI").
@@ -79,7 +79,8 @@ class SAPI extends Output implements Input {
   public function incoming() { return $this->incoming; }
 
   /**
-   * Returns parts from a multipart/form-data request
+   * Returns parts from a multipart/form-data request. Includes all request parameters
+   * up-front as there is no way to know the order in which they were originally passed.
    *
    * @see    https://www.php.net/manual/en/reserved.variables.files.php
    * @see    https://www.php.net/manual/en/ini.core.php#ini.sect.file-uploads
@@ -87,6 +88,9 @@ class SAPI extends Output implements Input {
    * @return iterable
    */
   public function parts($boundary) {
+    foreach ($_REQUEST as $name => $value) {
+      yield $name => new Param($name, [urlencode($value)]);
+    }
     foreach ($_FILES as $name => $file) {
       if (is_array($file['error'])) {
         $name.= '[]';
diff --git a/src/test/php/web/unittest/MultipartRequestTest.class.php b/src/test/php/web/unittest/MultipartRequestTest.class.php
index af87aff..3b47f35 100755
--- a/src/test/php/web/unittest/MultipartRequestTest.class.php
+++ b/src/test/php/web/unittest/MultipartRequestTest.class.php
@@ -100,6 +100,19 @@ class MultipartRequestTest extends TestCase {
     $this->assertEquals(['tc' => 'Checked', 'submit' => 'Upload'], $params);
   }
 
+  #[@test]
+  public function only_parameters_before_files_accessible_before_handling_files() {
+    $req= new Request(new TestInput('POST', '/', self::$MULTIPART, $this->multipart([
+      $this->param('tc', 'Checked'),
+      $this->file('first.txt', 'First'),
+      $this->param('submit', 'Upload')
+    ])));
+
+    $this->assertEquals(['tc' => 'Checked'], $req->params(), 'Before iterating parts');
+    iterator_count($req->multipart()->parts());
+    $this->assertEquals(['tc' => 'Checked', 'submit' => 'Upload'], $req->params(), 'When complete');
+  }
+
   #[@test, @values([
   #  ['/', []],
   #  ['/?a=b', ['a' => 'b']],

```

**Comment by thekid** [comment]
The application with which I integration-tested the patch is available here:

https://gist.github.com/thekid/3bb2b6cd099f58bce85fa8447103a833

**Comment by johannes85** [comment]
> 
> 
> You should be able to implement file upload handlers such as https://docs.djangoproject.com/en/3.1/topics/http/file-uploads/#upload-handlers by using filters:
> 
> ```
> use io\{File, Folder};
> use web\Filter;
> 
> class StoreFileUploads implements Filter {
> 
>   public function __construct(private Folder $storage) { }
> 
>   public function filter($request, $response, $invocation) {
>      if (null === ($upload= $req->multipart())) return $invocation->proceed($request, $response);
> 
>      $uploads= [];
>      foreach ($upload->files() as $name => $file) {
>        $target= new File($this->storage, uniqid());
>        $file->transfer($target);
>        $uploads[$name]= $target;
>      }
> 
>      try {
>        return $invocation->proceed($request->pass('uploads', $uploads), $response);
>      } finally {
>        foreach ($uploads as $file) {
>          $file->exists() || $file->delete();
>        }
>      }
>   }
> }
> ```
> 
> Then, attach these to your file upload route:
> 
> ```
> use web\{Application, Filters};
> 
> class Uploads extends Application {
> 
>   public function routes() {
>     $tmp= new Folder(...);
>     return ['/files' => new Filters([new StoreFileUploads($tmp)], function($req, $res) {
>        // Here, $req->params() will be have been merged and can be handled as usual
>        // TBI
>      })];
>   }
> }
> ```
> 
> Maybe we can add this to a small additional library (and maybe make it intelligent about storing smaller files to memory, and add upload progress meter handling). Would that be helpful?

Yes this would be helpful I think thats the solution we would implement if the "peek into multipart" soulution isn't enough.

**Pull request closed without merging**
